force-app/main/default/objects/Brand__c/Brand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Brand__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Brand__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Shipping_Option__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Option</label>
    <referenceTo>Shipping_Option__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Option__c/Shipping_Option__c.object-meta.xml
<CustomObject>
    <label>Shipping Option</label>
    <nameField>
        <label>Shipping Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductController.cls
public class ProductController {
    public ProductController() {

    }

    @AuraEnabled(cacheable=true)
    public static List<Product2> getAllProducts(){
        return (List<Product2>)[SELECT Id, 
                    Name, 
                    Price__c, 
                    Brand__c, 
                    Brand__r.Name, 
                    Shipping_Option__c, 
                    Shipping_Option__r.Name
                FROM Product2];
    }
}